### ISSUE TITLE
Add ANSI Keyboard support

### ISSUE THREAD

**Issue by Woyten** [Woyten/tune#27]
Add a keyboard mapping for [ANSI keyboards](https://en.wikipedia.org/wiki/Keyboard_layout#/media/File:Physical_keyboard_layouts_comparison_ANSI_ISO_KS_ABNT_JIS.png) s.t. adjacent keys map to adjacent virtual key coordinates.

**Comment by trains2050** [comment]
> Add a keyboard mapping for [ANSI keyboards](https://en.wikipedia.org/wiki/Keyboard_layout#/media/File:Physical_keyboard_layouts_comparison_ANSI_ISO_KS_ABNT_JIS.png) s.t. adjacent keys map to adjacent virtual key coordinates.

working on it now

**Comment by Woyten** [comment]
Awesome!

**Comment by Woyten** [comment]
@trains2050 Is there any update on this issue?

**Comment by Woyten** [comment]
To be released with microwave 0.28.0.
