### ISSUE TITLE
Microwave requires Vulkan-compatible graphics

### ISSUE THREAD

**Issue by x31eq** [Woyten/tune#37]
Running microwave fails because it's unable to open a graphics device

    [INFO] Loading waveforms file `waveforms.yml`
    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailableAdapter', microwave/src/main.rs:451:10
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    zsh: segmentation fault  microwave run

It looks like this is a known issue.  Vulkan assumes a reasonably powerful graphics card.  I have

    $ lspci | grep VGA    
    00:02.0 VGA compatible controller: Intel Corporation Core Processor Integrated Graphics Controller (rev 12)

A headless mode should at least allow the synth to run

**Comment by Woyten** [comment]
@x31eq Thanks for submitting the issue!

If I understand the [setup guide](https://www.guide.nannou.cc/getting_started/platform-specific_setup.html) correctly, your Intel graphics card should work once the vulkan drivers have been installed:

> For Debian with AMD or Intel graphic cards:
> `sudo apt-get install libvulkan1 mesa-vulkan-drivers vulkan-utils`

It might be worth checking whether switching between X11 and Wayland has an effect.

Bringing a headless mode to `microwave` is a very good idea. I will see what I can do here. It might not be straight-forward since processing input events seems to require some window context.

**Comment by Woyten** [comment]
@x31eq The underlying `wgpu` crate has been updated several times and comes with basic GL support. Could you check if the latest master branch works for you? If you prefer, I can trigger a test release job to build the binary for you.

**Comment by Woyten** [comment]
@x31eq I created a new release anyway: https://github.com/Woyten/tune/releases/tag/microwave-0.27.1

**Comment by x31eq** [comment]
On 05/12/2021, Woyten ***@***.***> wrote:
> @x31eq The underlying `wgpu` crate has been updated several times and comes
> with basic GL support. Could you check if the latest master branch works for
> you? If you prefer, I can trigger a test release job to build the binary for
> you.

I get a user interface now.  I'm not sure it's correct: it shows black
and white lines that look like the top of a piano keyboard.  I can't
get any sound out of it.

The command line says this:

WARNING: lavapipe is not a conformant vulkan implementation, testing use only.

If I un-maximize the window or change workspace I get a segfault.


                 Graham

**Comment by Woyten** [comment]
@x31eq Thanks for checking. If the UI is loaded correctly it should emit a sound once you click somewhere on the surface.

In case there is still a Vulkan-related problem: I just created a test release which enforces using a GL driver: https://github.com/Woyten/tune/releases/tag/microwave-gl-only Maybe this works better for you?

**Comment by x31eq** [comment]
Doesn't work for me.

thread 'main' panicked at 'called `Result::unwrap()` on an `Err`
value: NoAvailableAdapter', microwave/src/main.rs:504:10
stack backtrace:
   0: rust_begin_unwind
             at
/rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at
/rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/panicking.rs:100:14
   2: core::result::unwrap_failed
             at
/rustc/f1edd0429582dd29cccacaf50fd134b05593bd9c/library/core/src/result.rs:1616:5
   3: microwave::model
   4: nannou::app::Builder<M,E>::run
   5: microwave::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a
verbose backtrace.

**Comment by Woyten** [comment]
@x31eq Closing this since `microwave` will start using `bevy` in version `0.34.0`. `bevy` is a popular and well-maintained graphics engine with a strong focus on portability s.t. support for all relevant graphics adapters is expected.
