### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by tank-trax** [Woyten/tune#40]
Linux Mint 20.2

```
cargo b
error: failed to parse manifest at `~/src/tune/Cargo.toml`

Caused by:
  feature `edition2021` is required

  consider adding `cargo-features = ["edition2021"]` to the manifest
```

**Comment by tank-trax** [comment]
uninstalled cargo and rust from Synaptic and cleaned up with `sudo apt autoremove`

installed rust and cargo via `curl https://sh.rustup.rs -sSf | sh`

and is building now

**Comment by Woyten** [comment]
Thanks for documenting and explaining the fix. I prefer not to include this explanation in the README.md for the following reasons:

- This issue already explains well what to do and will help others.
- Using the packaged `rustc` is what most Rustlings get "wrong" (how should they know?) at the beginning. It's not limited to this repo.
- Even the packaged `rustc` will support `edition2021` in the future. `edition2021` uses clear error messages about the minimal required `rustc` version.
